package com.example.web22;

import java.util.ArrayList;
import java.util.List;

public class ArmyTreeDO {

    private Integer id;

    private String title;

    private Integer parentid;

    private List<ArmyTreeDO> children = new ArrayList<ArmyTreeDO>();

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column army_tree.id
     *
     * @param id the value for army_tree.id
     *
     * @mbg.generated Sun Oct 10 20:28:15 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column army_tree.title
     *
     * @return the value of army_tree.title
     *
     * @mbg.generated Sun Oct 10 20:28:15 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column army_tree.title
     *
     * @param title the value for army_tree.title
     *
     * @mbg.generated Sun Oct 10 20:28:15 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column army_tree.parentid
     *
     * @return the value of army_tree.parentid
     *
     * @mbg.generated Sun Oct 10 20:28:15 CST 2021
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column army_tree.parentid
     *
     * @param parentid the value for army_tree.parentid
     *
     * @mbg.generated Sun Oct 10 20:28:15 CST 2021
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    public List<ArmyTreeDO> getChildren() {
        return children;
    }

    public void setChildren(List<ArmyTreeDO> children) {
        this.children = children;
    }
}