package com.example.web22;

import java.util.ArrayList;
import java.util.List;

public class ArmyBaseDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table army_base_info
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table army_base_info
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table army_base_info
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_base_info
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public ArmyBaseDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_base_info
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_base_info
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_base_info
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_base_info
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_base_info
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_base_info
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_base_info
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_base_info
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_base_info
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_base_info
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table army_base_info
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andArmyidIsNull() {
            addCriterion("armyid is null");
            return (Criteria) this;
        }

        public Criteria andArmyidIsNotNull() {
            addCriterion("armyid is not null");
            return (Criteria) this;
        }

        public Criteria andArmyidEqualTo(Integer value) {
            addCriterion("armyid =", value, "armyid");
            return (Criteria) this;
        }

        public Criteria andArmyidNotEqualTo(Integer value) {
            addCriterion("armyid <>", value, "armyid");
            return (Criteria) this;
        }

        public Criteria andArmyidGreaterThan(Integer value) {
            addCriterion("armyid >", value, "armyid");
            return (Criteria) this;
        }

        public Criteria andArmyidGreaterThanOrEqualTo(Integer value) {
            addCriterion("armyid >=", value, "armyid");
            return (Criteria) this;
        }

        public Criteria andArmyidLessThan(Integer value) {
            addCriterion("armyid <", value, "armyid");
            return (Criteria) this;
        }

        public Criteria andArmyidLessThanOrEqualTo(Integer value) {
            addCriterion("armyid <=", value, "armyid");
            return (Criteria) this;
        }

        public Criteria andArmyidIn(List<Integer> values) {
            addCriterion("armyid in", values, "armyid");
            return (Criteria) this;
        }

        public Criteria andArmyidNotIn(List<Integer> values) {
            addCriterion("armyid not in", values, "armyid");
            return (Criteria) this;
        }

        public Criteria andArmyidBetween(Integer value1, Integer value2) {
            addCriterion("armyid between", value1, value2, "armyid");
            return (Criteria) this;
        }

        public Criteria andArmyidNotBetween(Integer value1, Integer value2) {
            addCriterion("armyid not between", value1, value2, "armyid");
            return (Criteria) this;
        }

        public Criteria andArmyloginnameIsNull() {
            addCriterion("armyloginname is null");
            return (Criteria) this;
        }

        public Criteria andArmyloginnameIsNotNull() {
            addCriterion("armyloginname is not null");
            return (Criteria) this;
        }

        public Criteria andArmyloginnameEqualTo(String value) {
            addCriterion("armyloginname =", value, "armyloginname");
            return (Criteria) this;
        }

        public Criteria andArmyloginnameNotEqualTo(String value) {
            addCriterion("armyloginname <>", value, "armyloginname");
            return (Criteria) this;
        }

        public Criteria andArmyloginnameGreaterThan(String value) {
            addCriterion("armyloginname >", value, "armyloginname");
            return (Criteria) this;
        }

        public Criteria andArmyloginnameGreaterThanOrEqualTo(String value) {
            addCriterion("armyloginname >=", value, "armyloginname");
            return (Criteria) this;
        }

        public Criteria andArmyloginnameLessThan(String value) {
            addCriterion("armyloginname <", value, "armyloginname");
            return (Criteria) this;
        }

        public Criteria andArmyloginnameLessThanOrEqualTo(String value) {
            addCriterion("armyloginname <=", value, "armyloginname");
            return (Criteria) this;
        }

        public Criteria andArmyloginnameLike(String value) {
            addCriterion("armyloginname like", value, "armyloginname");
            return (Criteria) this;
        }

        public Criteria andArmyloginnameNotLike(String value) {
            addCriterion("armyloginname not like", value, "armyloginname");
            return (Criteria) this;
        }

        public Criteria andArmyloginnameIn(List<String> values) {
            addCriterion("armyloginname in", values, "armyloginname");
            return (Criteria) this;
        }

        public Criteria andArmyloginnameNotIn(List<String> values) {
            addCriterion("armyloginname not in", values, "armyloginname");
            return (Criteria) this;
        }

        public Criteria andArmyloginnameBetween(String value1, String value2) {
            addCriterion("armyloginname between", value1, value2, "armyloginname");
            return (Criteria) this;
        }

        public Criteria andArmyloginnameNotBetween(String value1, String value2) {
            addCriterion("armyloginname not between", value1, value2, "armyloginname");
            return (Criteria) this;
        }

        public Criteria andArmynameIsNull() {
            addCriterion("armyname is null");
            return (Criteria) this;
        }

        public Criteria andArmynameIsNotNull() {
            addCriterion("armyname is not null");
            return (Criteria) this;
        }

        public Criteria andArmynameEqualTo(String value) {
            addCriterion("armyname =", value, "armyname");
            return (Criteria) this;
        }

        public Criteria andArmynameNotEqualTo(String value) {
            addCriterion("armyname <>", value, "armyname");
            return (Criteria) this;
        }

        public Criteria andArmynameGreaterThan(String value) {
            addCriterion("armyname >", value, "armyname");
            return (Criteria) this;
        }

        public Criteria andArmynameGreaterThanOrEqualTo(String value) {
            addCriterion("armyname >=", value, "armyname");
            return (Criteria) this;
        }

        public Criteria andArmynameLessThan(String value) {
            addCriterion("armyname <", value, "armyname");
            return (Criteria) this;
        }

        public Criteria andArmynameLessThanOrEqualTo(String value) {
            addCriterion("armyname <=", value, "armyname");
            return (Criteria) this;
        }

        public Criteria andArmynameLike(String value) {
            addCriterion("armyname like", value, "armyname");
            return (Criteria) this;
        }

        public Criteria andArmynameNotLike(String value) {
            addCriterion("armyname not like", value, "armyname");
            return (Criteria) this;
        }

        public Criteria andArmynameIn(List<String> values) {
            addCriterion("armyname in", values, "armyname");
            return (Criteria) this;
        }

        public Criteria andArmynameNotIn(List<String> values) {
            addCriterion("armyname not in", values, "armyname");
            return (Criteria) this;
        }

        public Criteria andArmynameBetween(String value1, String value2) {
            addCriterion("armyname between", value1, value2, "armyname");
            return (Criteria) this;
        }

        public Criteria andArmynameNotBetween(String value1, String value2) {
            addCriterion("armyname not between", value1, value2, "armyname");
            return (Criteria) this;
        }

        public Criteria andArmycontactIsNull() {
            addCriterion("armycontact is null");
            return (Criteria) this;
        }

        public Criteria andArmycontactIsNotNull() {
            addCriterion("armycontact is not null");
            return (Criteria) this;
        }

        public Criteria andArmycontactEqualTo(String value) {
            addCriterion("armycontact =", value, "armycontact");
            return (Criteria) this;
        }

        public Criteria andArmycontactNotEqualTo(String value) {
            addCriterion("armycontact <>", value, "armycontact");
            return (Criteria) this;
        }

        public Criteria andArmycontactGreaterThan(String value) {
            addCriterion("armycontact >", value, "armycontact");
            return (Criteria) this;
        }

        public Criteria andArmycontactGreaterThanOrEqualTo(String value) {
            addCriterion("armycontact >=", value, "armycontact");
            return (Criteria) this;
        }

        public Criteria andArmycontactLessThan(String value) {
            addCriterion("armycontact <", value, "armycontact");
            return (Criteria) this;
        }

        public Criteria andArmycontactLessThanOrEqualTo(String value) {
            addCriterion("armycontact <=", value, "armycontact");
            return (Criteria) this;
        }

        public Criteria andArmycontactLike(String value) {
            addCriterion("armycontact like", value, "armycontact");
            return (Criteria) this;
        }

        public Criteria andArmycontactNotLike(String value) {
            addCriterion("armycontact not like", value, "armycontact");
            return (Criteria) this;
        }

        public Criteria andArmycontactIn(List<String> values) {
            addCriterion("armycontact in", values, "armycontact");
            return (Criteria) this;
        }

        public Criteria andArmycontactNotIn(List<String> values) {
            addCriterion("armycontact not in", values, "armycontact");
            return (Criteria) this;
        }

        public Criteria andArmycontactBetween(String value1, String value2) {
            addCriterion("armycontact between", value1, value2, "armycontact");
            return (Criteria) this;
        }

        public Criteria andArmycontactNotBetween(String value1, String value2) {
            addCriterion("armycontact not between", value1, value2, "armycontact");
            return (Criteria) this;
        }

        public Criteria andArmytelIsNull() {
            addCriterion("armytel is null");
            return (Criteria) this;
        }

        public Criteria andArmytelIsNotNull() {
            addCriterion("armytel is not null");
            return (Criteria) this;
        }

        public Criteria andArmytelEqualTo(String value) {
            addCriterion("armytel =", value, "armytel");
            return (Criteria) this;
        }

        public Criteria andArmytelNotEqualTo(String value) {
            addCriterion("armytel <>", value, "armytel");
            return (Criteria) this;
        }

        public Criteria andArmytelGreaterThan(String value) {
            addCriterion("armytel >", value, "armytel");
            return (Criteria) this;
        }

        public Criteria andArmytelGreaterThanOrEqualTo(String value) {
            addCriterion("armytel >=", value, "armytel");
            return (Criteria) this;
        }

        public Criteria andArmytelLessThan(String value) {
            addCriterion("armytel <", value, "armytel");
            return (Criteria) this;
        }

        public Criteria andArmytelLessThanOrEqualTo(String value) {
            addCriterion("armytel <=", value, "armytel");
            return (Criteria) this;
        }

        public Criteria andArmytelLike(String value) {
            addCriterion("armytel like", value, "armytel");
            return (Criteria) this;
        }

        public Criteria andArmytelNotLike(String value) {
            addCriterion("armytel not like", value, "armytel");
            return (Criteria) this;
        }

        public Criteria andArmytelIn(List<String> values) {
            addCriterion("armytel in", values, "armytel");
            return (Criteria) this;
        }

        public Criteria andArmytelNotIn(List<String> values) {
            addCriterion("armytel not in", values, "armytel");
            return (Criteria) this;
        }

        public Criteria andArmytelBetween(String value1, String value2) {
            addCriterion("armytel between", value1, value2, "armytel");
            return (Criteria) this;
        }

        public Criteria andArmytelNotBetween(String value1, String value2) {
            addCriterion("armytel not between", value1, value2, "armytel");
            return (Criteria) this;
        }

        public Criteria andArmyabilityIsNull() {
            addCriterion("armyability is null");
            return (Criteria) this;
        }

        public Criteria andArmyabilityIsNotNull() {
            addCriterion("armyability is not null");
            return (Criteria) this;
        }

        public Criteria andArmyabilityEqualTo(Integer value) {
            addCriterion("armyability =", value, "armyability");
            return (Criteria) this;
        }

        public Criteria andArmyabilityNotEqualTo(Integer value) {
            addCriterion("armyability <>", value, "armyability");
            return (Criteria) this;
        }

        public Criteria andArmyabilityGreaterThan(Integer value) {
            addCriterion("armyability >", value, "armyability");
            return (Criteria) this;
        }

        public Criteria andArmyabilityGreaterThanOrEqualTo(Integer value) {
            addCriterion("armyability >=", value, "armyability");
            return (Criteria) this;
        }

        public Criteria andArmyabilityLessThan(Integer value) {
            addCriterion("armyability <", value, "armyability");
            return (Criteria) this;
        }

        public Criteria andArmyabilityLessThanOrEqualTo(Integer value) {
            addCriterion("armyability <=", value, "armyability");
            return (Criteria) this;
        }

        public Criteria andArmyabilityIn(List<Integer> values) {
            addCriterion("armyability in", values, "armyability");
            return (Criteria) this;
        }

        public Criteria andArmyabilityNotIn(List<Integer> values) {
            addCriterion("armyability not in", values, "armyability");
            return (Criteria) this;
        }

        public Criteria andArmyabilityBetween(Integer value1, Integer value2) {
            addCriterion("armyability between", value1, value2, "armyability");
            return (Criteria) this;
        }

        public Criteria andArmyabilityNotBetween(Integer value1, Integer value2) {
            addCriterion("armyability not between", value1, value2, "armyability");
            return (Criteria) this;
        }

        public Criteria andArmypropertiesIsNull() {
            addCriterion("armyproperties is null");
            return (Criteria) this;
        }

        public Criteria andArmypropertiesIsNotNull() {
            addCriterion("armyproperties is not null");
            return (Criteria) this;
        }

        public Criteria andArmypropertiesEqualTo(Integer value) {
            addCriterion("armyproperties =", value, "armyproperties");
            return (Criteria) this;
        }

        public Criteria andArmypropertiesNotEqualTo(Integer value) {
            addCriterion("armyproperties <>", value, "armyproperties");
            return (Criteria) this;
        }

        public Criteria andArmypropertiesGreaterThan(Integer value) {
            addCriterion("armyproperties >", value, "armyproperties");
            return (Criteria) this;
        }

        public Criteria andArmypropertiesGreaterThanOrEqualTo(Integer value) {
            addCriterion("armyproperties >=", value, "armyproperties");
            return (Criteria) this;
        }

        public Criteria andArmypropertiesLessThan(Integer value) {
            addCriterion("armyproperties <", value, "armyproperties");
            return (Criteria) this;
        }

        public Criteria andArmypropertiesLessThanOrEqualTo(Integer value) {
            addCriterion("armyproperties <=", value, "armyproperties");
            return (Criteria) this;
        }

        public Criteria andArmypropertiesIn(List<Integer> values) {
            addCriterion("armyproperties in", values, "armyproperties");
            return (Criteria) this;
        }

        public Criteria andArmypropertiesNotIn(List<Integer> values) {
            addCriterion("armyproperties not in", values, "armyproperties");
            return (Criteria) this;
        }

        public Criteria andArmypropertiesBetween(Integer value1, Integer value2) {
            addCriterion("armyproperties between", value1, value2, "armyproperties");
            return (Criteria) this;
        }

        public Criteria andArmypropertiesNotBetween(Integer value1, Integer value2) {
            addCriterion("armyproperties not between", value1, value2, "armyproperties");
            return (Criteria) this;
        }

        public Criteria andArmyareaIsNull() {
            addCriterion("armyarea is null");
            return (Criteria) this;
        }

        public Criteria andArmyareaIsNotNull() {
            addCriterion("armyarea is not null");
            return (Criteria) this;
        }

        public Criteria andArmyareaEqualTo(String value) {
            addCriterion("armyarea =", value, "armyarea");
            return (Criteria) this;
        }

        public Criteria andArmyareaNotEqualTo(String value) {
            addCriterion("armyarea <>", value, "armyarea");
            return (Criteria) this;
        }

        public Criteria andArmyareaGreaterThan(String value) {
            addCriterion("armyarea >", value, "armyarea");
            return (Criteria) this;
        }

        public Criteria andArmyareaGreaterThanOrEqualTo(String value) {
            addCriterion("armyarea >=", value, "armyarea");
            return (Criteria) this;
        }

        public Criteria andArmyareaLessThan(String value) {
            addCriterion("armyarea <", value, "armyarea");
            return (Criteria) this;
        }

        public Criteria andArmyareaLessThanOrEqualTo(String value) {
            addCriterion("armyarea <=", value, "armyarea");
            return (Criteria) this;
        }

        public Criteria andArmyareaLike(String value) {
            addCriterion("armyarea like", value, "armyarea");
            return (Criteria) this;
        }

        public Criteria andArmyareaNotLike(String value) {
            addCriterion("armyarea not like", value, "armyarea");
            return (Criteria) this;
        }

        public Criteria andArmyareaIn(List<String> values) {
            addCriterion("armyarea in", values, "armyarea");
            return (Criteria) this;
        }

        public Criteria andArmyareaNotIn(List<String> values) {
            addCriterion("armyarea not in", values, "armyarea");
            return (Criteria) this;
        }

        public Criteria andArmyareaBetween(String value1, String value2) {
            addCriterion("armyarea between", value1, value2, "armyarea");
            return (Criteria) this;
        }

        public Criteria andArmyareaNotBetween(String value1, String value2) {
            addCriterion("armyarea not between", value1, value2, "armyarea");
            return (Criteria) this;
        }

        public Criteria andLoginpwdIsNull() {
            addCriterion("loginpwd is null");
            return (Criteria) this;
        }

        public Criteria andLoginpwdIsNotNull() {
            addCriterion("loginpwd is not null");
            return (Criteria) this;
        }

        public Criteria andLoginpwdEqualTo(String value) {
            addCriterion("loginpwd =", value, "loginpwd");
            return (Criteria) this;
        }

        public Criteria andLoginpwdNotEqualTo(String value) {
            addCriterion("loginpwd <>", value, "loginpwd");
            return (Criteria) this;
        }

        public Criteria andLoginpwdGreaterThan(String value) {
            addCriterion("loginpwd >", value, "loginpwd");
            return (Criteria) this;
        }

        public Criteria andLoginpwdGreaterThanOrEqualTo(String value) {
            addCriterion("loginpwd >=", value, "loginpwd");
            return (Criteria) this;
        }

        public Criteria andLoginpwdLessThan(String value) {
            addCriterion("loginpwd <", value, "loginpwd");
            return (Criteria) this;
        }

        public Criteria andLoginpwdLessThanOrEqualTo(String value) {
            addCriterion("loginpwd <=", value, "loginpwd");
            return (Criteria) this;
        }

        public Criteria andLoginpwdLike(String value) {
            addCriterion("loginpwd like", value, "loginpwd");
            return (Criteria) this;
        }

        public Criteria andLoginpwdNotLike(String value) {
            addCriterion("loginpwd not like", value, "loginpwd");
            return (Criteria) this;
        }

        public Criteria andLoginpwdIn(List<String> values) {
            addCriterion("loginpwd in", values, "loginpwd");
            return (Criteria) this;
        }

        public Criteria andLoginpwdNotIn(List<String> values) {
            addCriterion("loginpwd not in", values, "loginpwd");
            return (Criteria) this;
        }

        public Criteria andLoginpwdBetween(String value1, String value2) {
            addCriterion("loginpwd between", value1, value2, "loginpwd");
            return (Criteria) this;
        }

        public Criteria andLoginpwdNotBetween(String value1, String value2) {
            addCriterion("loginpwd not between", value1, value2, "loginpwd");
            return (Criteria) this;
        }

        public Criteria andContactinfoIsNull() {
            addCriterion("contactinfo is null");
            return (Criteria) this;
        }

        public Criteria andContactinfoIsNotNull() {
            addCriterion("contactinfo is not null");
            return (Criteria) this;
        }

        public Criteria andContactinfoEqualTo(String value) {
            addCriterion("contactinfo =", value, "contactinfo");
            return (Criteria) this;
        }

        public Criteria andContactinfoNotEqualTo(String value) {
            addCriterion("contactinfo <>", value, "contactinfo");
            return (Criteria) this;
        }

        public Criteria andContactinfoGreaterThan(String value) {
            addCriterion("contactinfo >", value, "contactinfo");
            return (Criteria) this;
        }

        public Criteria andContactinfoGreaterThanOrEqualTo(String value) {
            addCriterion("contactinfo >=", value, "contactinfo");
            return (Criteria) this;
        }

        public Criteria andContactinfoLessThan(String value) {
            addCriterion("contactinfo <", value, "contactinfo");
            return (Criteria) this;
        }

        public Criteria andContactinfoLessThanOrEqualTo(String value) {
            addCriterion("contactinfo <=", value, "contactinfo");
            return (Criteria) this;
        }

        public Criteria andContactinfoLike(String value) {
            addCriterion("contactinfo like", value, "contactinfo");
            return (Criteria) this;
        }

        public Criteria andContactinfoNotLike(String value) {
            addCriterion("contactinfo not like", value, "contactinfo");
            return (Criteria) this;
        }

        public Criteria andContactinfoIn(List<String> values) {
            addCriterion("contactinfo in", values, "contactinfo");
            return (Criteria) this;
        }

        public Criteria andContactinfoNotIn(List<String> values) {
            addCriterion("contactinfo not in", values, "contactinfo");
            return (Criteria) this;
        }

        public Criteria andContactinfoBetween(String value1, String value2) {
            addCriterion("contactinfo between", value1, value2, "contactinfo");
            return (Criteria) this;
        }

        public Criteria andContactinfoNotBetween(String value1, String value2) {
            addCriterion("contactinfo not between", value1, value2, "contactinfo");
            return (Criteria) this;
        }

        public Criteria andFundsIsNull() {
            addCriterion("funds is null");
            return (Criteria) this;
        }

        public Criteria andFundsIsNotNull() {
            addCriterion("funds is not null");
            return (Criteria) this;
        }

        public Criteria andFundsEqualTo(String value) {
            addCriterion("funds =", value, "funds");
            return (Criteria) this;
        }

        public Criteria andFundsNotEqualTo(String value) {
            addCriterion("funds <>", value, "funds");
            return (Criteria) this;
        }

        public Criteria andFundsGreaterThan(String value) {
            addCriterion("funds >", value, "funds");
            return (Criteria) this;
        }

        public Criteria andFundsGreaterThanOrEqualTo(String value) {
            addCriterion("funds >=", value, "funds");
            return (Criteria) this;
        }

        public Criteria andFundsLessThan(String value) {
            addCriterion("funds <", value, "funds");
            return (Criteria) this;
        }

        public Criteria andFundsLessThanOrEqualTo(String value) {
            addCriterion("funds <=", value, "funds");
            return (Criteria) this;
        }

        public Criteria andFundsLike(String value) {
            addCriterion("funds like", value, "funds");
            return (Criteria) this;
        }

        public Criteria andFundsNotLike(String value) {
            addCriterion("funds not like", value, "funds");
            return (Criteria) this;
        }

        public Criteria andFundsIn(List<String> values) {
            addCriterion("funds in", values, "funds");
            return (Criteria) this;
        }

        public Criteria andFundsNotIn(List<String> values) {
            addCriterion("funds not in", values, "funds");
            return (Criteria) this;
        }

        public Criteria andFundsBetween(String value1, String value2) {
            addCriterion("funds between", value1, value2, "funds");
            return (Criteria) this;
        }

        public Criteria andFundsNotBetween(String value1, String value2) {
            addCriterion("funds not between", value1, value2, "funds");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table army_base_info
     *
     * @mbg.generated do_not_delete_during_merge Sun Oct 10 18:40:47 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table army_base_info
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}