package com.example.web22;

public class ArmyBaseDO {

    private Integer armyid;

    private String armyloginname;

    private String armyname;

    private String armycontact;

    private String armytel;

    private Integer armyability;

    private Integer armyproperties;

    private String armyarea;

    private String loginpwd;

    private String contactinfo;

    private String funds;

    private ArmyAbilityDO armyAbilityDO = new ArmyAbilityDO();

    public ArmyAbilityDO getArmyAbilityDO(){
        return armyAbilityDO;
    }

    public void setArmyAbilityDO(ArmyAbilityDO armyAbilityDO){
        this.armyAbilityDO = armyAbilityDO;
    }

    private ArmyPropDO propDO = new ArmyPropDO();

    public ArmyPropDO getPropDO(){
        return propDO;
    }

    public Integer getArmyid() {
        return armyid;
    }

    public void setArmyid(Integer armyid) {
        this.armyid = armyid;
    }

    public String getArmyloginname() {
        return armyloginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column army_base_info.armyloginname
     *
     * @param armyloginname the value for army_base_info.armyloginname
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public void setArmyloginname(String armyloginname) {
        this.armyloginname = armyloginname == null ? null : armyloginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column army_base_info.armyname
     *
     * @return the value of army_base_info.armyname
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public String getArmyname() {
        return armyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column army_base_info.armyname
     *
     * @param armyname the value for army_base_info.armyname
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public void setArmyname(String armyname) {
        this.armyname = armyname == null ? null : armyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column army_base_info.armycontact
     *
     * @return the value of army_base_info.armycontact
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public String getArmycontact() {
        return armycontact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column army_base_info.armycontact
     *
     * @param armycontact the value for army_base_info.armycontact
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public void setArmycontact(String armycontact) {
        this.armycontact = armycontact == null ? null : armycontact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column army_base_info.armytel
     *
     * @return the value of army_base_info.armytel
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public String getArmytel() {
        return armytel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column army_base_info.armytel
     *
     * @param armytel the value for army_base_info.armytel
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public void setArmytel(String armytel) {
        this.armytel = armytel == null ? null : armytel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column army_base_info.armyability
     *
     * @return the value of army_base_info.armyability
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public Integer getArmyability() {
        return armyability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column army_base_info.armyability
     *
     * @param armyability the value for army_base_info.armyability
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public void setArmyability(Integer armyability) {
        this.armyability = armyability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column army_base_info.armyproperties
     *
     * @return the value of army_base_info.armyproperties
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public Integer getArmyproperties() {
        return armyproperties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column army_base_info.armyproperties
     *
     * @param armyproperties the value for army_base_info.armyproperties
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public void setArmyproperties(Integer armyproperties) {
        this.armyproperties = armyproperties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column army_base_info.armyarea
     *
     * @return the value of army_base_info.armyarea
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public String getArmyarea() {
        return armyarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column army_base_info.armyarea
     *
     * @param armyarea the value for army_base_info.armyarea
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public void setArmyarea(String armyarea) {
        this.armyarea = armyarea == null ? null : armyarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column army_base_info.loginpwd
     *
     * @return the value of army_base_info.loginpwd
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public String getLoginpwd() {
        return loginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column army_base_info.loginpwd
     *
     * @param loginpwd the value for army_base_info.loginpwd
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public void setLoginpwd(String loginpwd) {
        this.loginpwd = loginpwd == null ? null : loginpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column army_base_info.contactinfo
     *
     * @return the value of army_base_info.contactinfo
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public String getContactinfo() {
        return contactinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column army_base_info.contactinfo
     *
     * @param contactinfo the value for army_base_info.contactinfo
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public void setContactinfo(String contactinfo) {
        this.contactinfo = contactinfo == null ? null : contactinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column army_base_info.funds
     *
     * @return the value of army_base_info.funds
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public String getFunds() {
        return funds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column army_base_info.funds
     *
     * @param funds the value for army_base_info.funds
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    public void setFunds(String funds) {
        this.funds = funds == null ? null : funds.trim();
    }

    @Override
    public String toString(){
        return "ArmyBaseDO{" +
                "armyid=" + armyid +
                ",armyname='"+armyname+'\''+
                ",armycontact='"+armycontact+'\''+
                ",armytel='"+armytel+'\''+
                ",armyability='"+armyability+'\''+
                ",armyproperties='"+armyproperties+'\''+
                ",armyarea='"+armyarea+'\''+
                ",loginpwd='"+loginpwd+'\''+
                ",contactinfo='"+contactinfo+'\''+
                ",funds='"+funds+'\''+
                '}';
    }
}