package com.example.web22;

public class DwyqsdDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwyqsd.id
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwyqsd.zb
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    private String zb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwyqsd.wz
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    private String wz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwyqsd.ry
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    private String ry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwyqsd.xl
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    private String xl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwyqsd.time
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwyqsd.id
     *
     * @return the value of dwyqsd.id
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwyqsd.id
     *
     * @param id the value for dwyqsd.id
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwyqsd.zb
     *
     * @return the value of dwyqsd.zb
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    public String getZb() {
        return zb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwyqsd.zb
     *
     * @param zb the value for dwyqsd.zb
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    public void setZb(String zb) {
        this.zb = zb == null ? null : zb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwyqsd.wz
     *
     * @return the value of dwyqsd.wz
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    public String getWz() {
        return wz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwyqsd.wz
     *
     * @param wz the value for dwyqsd.wz
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    public void setWz(String wz) {
        this.wz = wz == null ? null : wz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwyqsd.ry
     *
     * @return the value of dwyqsd.ry
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    public String getRy() {
        return ry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwyqsd.ry
     *
     * @param ry the value for dwyqsd.ry
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    public void setRy(String ry) {
        this.ry = ry == null ? null : ry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwyqsd.xl
     *
     * @return the value of dwyqsd.xl
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    public String getXl() {
        return xl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwyqsd.xl
     *
     * @param xl the value for dwyqsd.xl
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    public void setXl(String xl) {
        this.xl = xl == null ? null : xl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwyqsd.time
     *
     * @return the value of dwyqsd.time
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwyqsd.time
     *
     * @param time the value for dwyqsd.time
     *
     * @mbg.generated Sat Oct 16 15:25:13 CST 2021
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}