package com.example.web22;

public class OrganizeDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.id
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.name
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.sex
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.home
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    private String home;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.id
     *
     * @return the value of organize.id
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.id
     *
     * @param id the value for organize.id
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.name
     *
     * @return the value of organize.name
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.name
     *
     * @param name the value for organize.name
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.sex
     *
     * @return the value of organize.sex
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.sex
     *
     * @param sex the value for organize.sex
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.home
     *
     * @return the value of organize.home
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    public String getHome() {
        return home;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.home
     *
     * @param home the value for organize.home
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    public void setHome(String home) {
        this.home = home == null ? null : home.trim();
    }
}