package com.example.web22;

public class UserJcyjDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_jcyj.id
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_jcyj.name
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_jcyj.time
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_jcyj.overtime
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    private Integer overtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_jcyj.caution
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    private Integer caution;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_jcyj.id
     *
     * @return the value of user_jcyj.id
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_jcyj.id
     *
     * @param id the value for user_jcyj.id
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_jcyj.name
     *
     * @return the value of user_jcyj.name
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_jcyj.name
     *
     * @param name the value for user_jcyj.name
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_jcyj.time
     *
     * @return the value of user_jcyj.time
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_jcyj.time
     *
     * @param time the value for user_jcyj.time
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_jcyj.overtime
     *
     * @return the value of user_jcyj.overtime
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    public Integer getOvertime() {
        return overtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_jcyj.overtime
     *
     * @param overtime the value for user_jcyj.overtime
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    public void setOvertime(Integer overtime) {
        this.overtime = overtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_jcyj.caution
     *
     * @return the value of user_jcyj.caution
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    public Integer getCaution() {
        return caution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_jcyj.caution
     *
     * @param caution the value for user_jcyj.caution
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    public void setCaution(Integer caution) {
        this.caution = caution;
    }
}