package com.example.web22;

public class UserXxcxDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_xxcx.id
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_xxcx.teamName
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    private String teamname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_xxcx.sos
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    private String sos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_xxcx.place
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_xxcx.bigEquip
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    private String bigequip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_xxcx.ability
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    private String ability;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_xxcx.smallEquip
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    private String smallequip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_xxcx.id
     *
     * @return the value of user_xxcx.id
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_xxcx.id
     *
     * @param id the value for user_xxcx.id
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_xxcx.teamName
     *
     * @return the value of user_xxcx.teamName
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    public String getTeamname() {
        return teamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_xxcx.teamName
     *
     * @param teamname the value for user_xxcx.teamName
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    public void setTeamname(String teamname) {
        this.teamname = teamname == null ? null : teamname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_xxcx.sos
     *
     * @return the value of user_xxcx.sos
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    public String getSos() {
        return sos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_xxcx.sos
     *
     * @param sos the value for user_xxcx.sos
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    public void setSos(String sos) {
        this.sos = sos == null ? null : sos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_xxcx.place
     *
     * @return the value of user_xxcx.place
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_xxcx.place
     *
     * @param place the value for user_xxcx.place
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_xxcx.bigEquip
     *
     * @return the value of user_xxcx.bigEquip
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    public String getBigequip() {
        return bigequip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_xxcx.bigEquip
     *
     * @param bigequip the value for user_xxcx.bigEquip
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    public void setBigequip(String bigequip) {
        this.bigequip = bigequip == null ? null : bigequip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_xxcx.ability
     *
     * @return the value of user_xxcx.ability
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    public String getAbility() {
        return ability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_xxcx.ability
     *
     * @param ability the value for user_xxcx.ability
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    public void setAbility(String ability) {
        this.ability = ability == null ? null : ability.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_xxcx.smallEquip
     *
     * @return the value of user_xxcx.smallEquip
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    public String getSmallequip() {
        return smallequip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_xxcx.smallEquip
     *
     * @param smallequip the value for user_xxcx.smallEquip
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    public void setSmallequip(String smallequip) {
        this.smallequip = smallequip == null ? null : smallequip.trim();
    }
}