package com.example.web22;

import java.util.Date;

public class ZbxxglDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zbxxgl.id
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zbxxgl.uname
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zbxxgl.model
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zbxxgl.factory
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    private String factory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zbxxgl.time
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zbxxgl.number
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zbxxgl.state
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zbxxgl.id
     *
     * @return the value of zbxxgl.id
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zbxxgl.id
     *
     * @param id the value for zbxxgl.id
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zbxxgl.uname
     *
     * @return the value of zbxxgl.uname
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zbxxgl.uname
     *
     * @param uname the value for zbxxgl.uname
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zbxxgl.model
     *
     * @return the value of zbxxgl.model
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zbxxgl.model
     *
     * @param model the value for zbxxgl.model
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zbxxgl.factory
     *
     * @return the value of zbxxgl.factory
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    public String getFactory() {
        return factory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zbxxgl.factory
     *
     * @param factory the value for zbxxgl.factory
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    public void setFactory(String factory) {
        this.factory = factory == null ? null : factory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zbxxgl.time
     *
     * @return the value of zbxxgl.time
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zbxxgl.time
     *
     * @param time the value for zbxxgl.time
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zbxxgl.number
     *
     * @return the value of zbxxgl.number
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zbxxgl.number
     *
     * @param number the value for zbxxgl.number
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zbxxgl.state
     *
     * @return the value of zbxxgl.state
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zbxxgl.state
     *
     * @param state the value for zbxxgl.state
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }
}