package com.example.web22.dao;

import com.example.web22.AccountNumberDO;
import com.example.web22.AccountNumberDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountNumberDOMapper {
    void updPassword (AccountNumberDO accountNumberDO);
    
    List<AccountNumberDO> listAllInfo(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwzhgl
     *
     * @mbg.generated Tue Oct 12 17:14:18 CST 2021
     */
    long countByExample(AccountNumberDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwzhgl
     *
     * @mbg.generated Tue Oct 12 17:14:18 CST 2021
     */
    int deleteByExample(AccountNumberDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwzhgl
     *
     * @mbg.generated Tue Oct 12 17:14:18 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwzhgl
     *
     * @mbg.generated Tue Oct 12 17:14:18 CST 2021
     */
    int insert(AccountNumberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwzhgl
     *
     * @mbg.generated Tue Oct 12 17:14:18 CST 2021
     */
    int insertSelective(AccountNumberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwzhgl
     *
     * @mbg.generated Tue Oct 12 17:14:18 CST 2021
     */
    List<AccountNumberDO> selectByExample(AccountNumberDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwzhgl
     *
     * @mbg.generated Tue Oct 12 17:14:18 CST 2021
     */
    AccountNumberDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwzhgl
     *
     * @mbg.generated Tue Oct 12 17:14:18 CST 2021
     */
    int updateByExampleSelective(@Param("record") AccountNumberDO record, @Param("example") AccountNumberDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwzhgl
     *
     * @mbg.generated Tue Oct 12 17:14:18 CST 2021
     */
    int updateByExample(@Param("record") AccountNumberDO record, @Param("example") AccountNumberDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwzhgl
     *
     * @mbg.generated Tue Oct 12 17:14:18 CST 2021
     */
    int updateByPrimaryKeySelective(AccountNumberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwzhgl
     *
     * @mbg.generated Tue Oct 12 17:14:18 CST 2021
     */
    int updateByPrimaryKey(AccountNumberDO record);
}