package com.example.web22.dao;

import com.example.web22.ArmyPropDO;
import com.example.web22.ArmyPropDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArmyPropDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_prop
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    long countByExample(ArmyPropDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_prop
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    int deleteByExample(ArmyPropDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_prop
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    int deleteByPrimaryKey(Integer propid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_prop
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    int insert(ArmyPropDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_prop
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    int insertSelective(ArmyPropDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_prop
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    List<ArmyPropDO> selectByExample(ArmyPropDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_prop
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    ArmyPropDO selectByPrimaryKey(Integer propid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_prop
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    int updateByExampleSelective(@Param("record") ArmyPropDO record, @Param("example") ArmyPropDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_prop
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    int updateByExample(@Param("record") ArmyPropDO record, @Param("example") ArmyPropDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_prop
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    int updateByPrimaryKeySelective(ArmyPropDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_prop
     *
     * @mbg.generated Sun Oct 10 18:40:47 CST 2021
     */
    int updateByPrimaryKey(ArmyPropDO record);
}