package com.example.web22.dao;

import com.example.web22.ArmyTreeDO;
import com.example.web22.ArmyTreeDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArmyTreeDOMapper {

    List<ArmyTreeDO> listAllInfo(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_tree
     *
     * @mbg.generated Sun Oct 10 20:28:15 CST 2021
     */
    long countByExample(ArmyTreeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_tree
     *
     * @mbg.generated Sun Oct 10 20:28:15 CST 2021
     */
    int deleteByExample(ArmyTreeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_tree
     *
     * @mbg.generated Sun Oct 10 20:28:15 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_tree
     *
     * @mbg.generated Sun Oct 10 20:28:15 CST 2021
     */
    int insert(ArmyTreeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_tree
     *
     * @mbg.generated Sun Oct 10 20:28:15 CST 2021
     */
    int insertSelective(ArmyTreeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_tree
     *
     * @mbg.generated Sun Oct 10 20:28:15 CST 2021
     */
    List<ArmyTreeDO> selectByExample(ArmyTreeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_tree
     *
     * @mbg.generated Sun Oct 10 20:28:15 CST 2021
     */
    ArmyTreeDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_tree
     *
     * @mbg.generated Sun Oct 10 20:28:15 CST 2021
     */
    int updateByExampleSelective(@Param("record") ArmyTreeDO record, @Param("example") ArmyTreeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_tree
     *
     * @mbg.generated Sun Oct 10 20:28:15 CST 2021
     */
    int updateByExample(@Param("record") ArmyTreeDO record, @Param("example") ArmyTreeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_tree
     *
     * @mbg.generated Sun Oct 10 20:28:15 CST 2021
     */
    int updateByPrimaryKeySelective(ArmyTreeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table army_tree
     *
     * @mbg.generated Sun Oct 10 20:28:15 CST 2021
     */
    int updateByPrimaryKey(ArmyTreeDO record);
}