package com.example.web22.dao;

import com.example.web22.ImageUploadDO;
import com.example.web22.ImageUploadDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImageUploadDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_imgupload
     *
     * @mbg.generated Wed Oct 13 22:18:11 CST 2021
     */
    long countByExample(ImageUploadDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_imgupload
     *
     * @mbg.generated Wed Oct 13 22:18:11 CST 2021
     */
    int deleteByExample(ImageUploadDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_imgupload
     *
     * @mbg.generated Wed Oct 13 22:18:11 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_imgupload
     *
     * @mbg.generated Wed Oct 13 22:18:11 CST 2021
     */
    int insert(ImageUploadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_imgupload
     *
     * @mbg.generated Wed Oct 13 22:18:11 CST 2021
     */
    int insertSelective(ImageUploadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_imgupload
     *
     * @mbg.generated Wed Oct 13 22:18:11 CST 2021
     */
    List<ImageUploadDO> selectByExample(ImageUploadDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_imgupload
     *
     * @mbg.generated Wed Oct 13 22:18:11 CST 2021
     */
    ImageUploadDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_imgupload
     *
     * @mbg.generated Wed Oct 13 22:18:11 CST 2021
     */
    int updateByExampleSelective(@Param("record") ImageUploadDO record, @Param("example") ImageUploadDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_imgupload
     *
     * @mbg.generated Wed Oct 13 22:18:11 CST 2021
     */
    int updateByExample(@Param("record") ImageUploadDO record, @Param("example") ImageUploadDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_imgupload
     *
     * @mbg.generated Wed Oct 13 22:18:11 CST 2021
     */
    int updateByPrimaryKeySelective(ImageUploadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_imgupload
     *
     * @mbg.generated Wed Oct 13 22:18:11 CST 2021
     */
    int updateByPrimaryKey(ImageUploadDO record);
}