package com.example.web22.dao;

import com.example.web22.OrganizeDo;
import com.example.web22.OrganizeDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrganizeDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    long countByExample(OrganizeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    int deleteByExample(OrganizeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    int insert(OrganizeDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    int insertSelective(OrganizeDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    List<OrganizeDo> selectByExample(OrganizeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    OrganizeDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    int updateByExampleSelective(@Param("record") OrganizeDo record, @Param("example") OrganizeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    int updateByExample(@Param("record") OrganizeDo record, @Param("example") OrganizeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    int updateByPrimaryKeySelective(OrganizeDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    int updateByPrimaryKey(OrganizeDo record);

    void updateInfo(OrganizeDo organize);
}