package com.example.web22.dao;

import com.example.web22.TabYlglDo;
import com.example.web22.TabYlglDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TabYlglDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_ylgl
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    long countByExample(TabYlglDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_ylgl
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    int deleteByExample(TabYlglDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_ylgl
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_ylgl
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    int insert(TabYlglDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_ylgl
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    int insertSelective(TabYlglDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_ylgl
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    List<TabYlglDo> selectByExample(TabYlglDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_ylgl
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    TabYlglDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_ylgl
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    int updateByExampleSelective(@Param("record") TabYlglDo record, @Param("example") TabYlglDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_ylgl
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    int updateByExample(@Param("record") TabYlglDo record, @Param("example") TabYlglDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_ylgl
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    int updateByPrimaryKeySelective(TabYlglDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_ylgl
     *
     * @mbg.generated Thu Oct 14 15:58:22 CST 2021
     */
    int updateByPrimaryKey(TabYlglDo record);

    void updateInfo(TabYlglDo tabylgl);
}