package com.example.web22.dao;

import com.example.web22.UserJcyjDo;
import com.example.web22.UserJcyjDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserJcyjDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_jcyj
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    long countByExample(UserJcyjDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_jcyj
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    int deleteByExample(UserJcyjDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_jcyj
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_jcyj
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    int insert(UserJcyjDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_jcyj
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    int insertSelective(UserJcyjDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_jcyj
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    List<UserJcyjDo> selectByExample(UserJcyjDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_jcyj
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    UserJcyjDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_jcyj
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserJcyjDo record, @Param("example") UserJcyjDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_jcyj
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    int updateByExample(@Param("record") UserJcyjDo record, @Param("example") UserJcyjDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_jcyj
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    int updateByPrimaryKeySelective(UserJcyjDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_jcyj
     *
     * @mbg.generated Thu Oct 14 20:21:06 CST 2021
     */
    int updateByPrimaryKey(UserJcyjDo record);
}