package com.example.web22.dao;

import com.example.web22.UserXxcxDo;
import com.example.web22.UserXxcxDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserXxcxDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_xxcx
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    long countByExample(UserXxcxDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_xxcx
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    int deleteByExample(UserXxcxDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_xxcx
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_xxcx
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    int insert(UserXxcxDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_xxcx
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    int insertSelective(UserXxcxDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_xxcx
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    List<UserXxcxDo> selectByExample(UserXxcxDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_xxcx
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    UserXxcxDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_xxcx
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserXxcxDo record, @Param("example") UserXxcxDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_xxcx
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    int updateByExample(@Param("record") UserXxcxDo record, @Param("example") UserXxcxDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_xxcx
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    int updateByPrimaryKeySelective(UserXxcxDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_xxcx
     *
     * @mbg.generated Thu Oct 14 20:18:43 CST 2021
     */
    int updateByPrimaryKey(UserXxcxDo record);
}