package com.example.web22.dao;

import com.example.web22.ZbxxglDo;
import com.example.web22.ZbxxglDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZbxxglDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbxxgl
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    long countByExample(ZbxxglDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbxxgl
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    int deleteByExample(ZbxxglDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbxxgl
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbxxgl
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    int insert(ZbxxglDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbxxgl
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    int insertSelective(ZbxxglDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbxxgl
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    List<ZbxxglDo> selectByExample(ZbxxglDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbxxgl
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    ZbxxglDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbxxgl
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    int updateByExampleSelective(@Param("record") ZbxxglDo record, @Param("example") ZbxxglDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbxxgl
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    int updateByExample(@Param("record") ZbxxglDo record, @Param("example") ZbxxglDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbxxgl
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    int updateByPrimaryKeySelective(ZbxxglDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbxxgl
     *
     * @mbg.generated Thu Oct 14 18:46:28 CST 2021
     */
    int updateByPrimaryKey(ZbxxglDo record);

}